/mv_camera:
  ros__parameters:
    camera_info_url: package://mindvision_camera/config/camera_info.yaml
    camera_name: mv_camera

    analog_gain: 32
    exposure_time: 6000

    rgb_gain:
      b: 120
      g: 110
      r: 135

    saturation: 100
    gamma: 100

    use_sensor_data_qos: true
